- name: Install packages to allow apt to use a repository over HTTPS
  become: yes
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes
- name: Add Docker’s official GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker apt repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
    update_cache: yes
- name: Install Docker Engine
  become: yes
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
- name: Create the docker group
  become: yes
  group:
    name: docker
    state: present
- name: Add vagrant user to docker group
  become: yes
  user:
    name: vagrant
    groups: docker
    append: yes
- name: Install bash completion
  become: yes
  apt:
    pkg: bash-completion
    update_cache: yes
- name: Add Docker bash completion
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker
    dest: /etc/bash_completion.d/docker.sh
- name: Ensure the docker service is enabled and started
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes